### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by cr4sh-me** [Magisk-Modules-Alt-Repo/Malwack#1]
Unzip error while trying latest release

![Screenshot_20230903-222628.png](https://github.com/Magisk-Modules-Alt-Repo/Malwack/assets/111238843/6ad84f73-103e-4a53-abaa-317bce35cf85)

**Comment by Person0z** [comment]
Did you install from the releases? or did you zip it yourself and install?

**Comment by cr4sh-me** [comment]
> Did you install from the releases? or did you zip it yourself and install?

From releases

**Comment by Person0z** [comment]
Okay, give me a minute and ill get it fixed. Ill comment and let you know when its done and fixed!

**Comment by Person0z** [comment]
Alright, it should be fixed! Sorry about that. @cr4sh-me

**Comment by cr4sh-me** [comment]
> Alright, it should be fixed! Sorry about that. @cr4sh-me 

Yes, it's working now. Thanks
