### ISSUE TITLE
Many websites won't open 

### ISSUE THREAD

**Issue by manishmani2004** [Magisk-Modules-Alt-Repo/Malwack#11]
It restricts many websites
from opening like Rado
automberg fans,etc

**Comment by daedaevibin** [comment]
Use Termux to adjust the whitelist and ensure malwack is up to date. Install Termux (F-Droid) update with `pkg update` and the `pkg install root-repo` then `su` then `malwack --restore-default` followed by `malwack --whitelist <domain>` and replace `<domain>` with the URL of the site you wish to use.

**Comment by Person0z** [comment]
Hello, allowlist means it will remove a blocked domain from the hosting list. If you want to access a website, follow the steps before and use the malwack commands to remove the host's file to its original and then access it. Once you are done, restore the default version.
