### ISSUE TITLE
Question/Request

### ISSUE THREAD

**Issue by daedaevibin** [Magisk-Modules-Alt-Repo/Malwack#12]
Will there be a Shizuku module for Malwack? I really think there should be because my friend who would really love to use malwack has a Samsung device that is non-rootable. (It's an S21 5G Snapdragon Variant) It is non-rootable because there is no bootloader or fastboot mode to root through, only download mode. It would be very nice if there could be a Shizuku version of the module.

**Comment by Person0z** [comment]
No, I don't know how to make a module for Shizuku. Additionally, the app is not too well known to make an effort to learn it and make the module.

**Comment by daedaevibin** [comment]
> No, I don't know how to make a module for Shizuku. Additionally, the app is not too well known to make an effort to learn it and make the module.

That truly makes a lot of sense. Then in effort to support you to the best of my ability I will spread as much word of Malwack as possible to Magisk users, carefully of course. I hope you receive enough support in the future to make a Shizuku version. Other than that, amazing module.

**Comment by Person0z** [comment]
Yep, thank you very much. Means a lot to me :) 

Hopefully in the future I may have a reason to make a module then, thank you!
