### ISSUE TITLE
Cannot install module 

### ISSUE THREAD

**Issue by U0101100** [Magisk-Modules-Alt-Repo/Malwack#13]
Cannot install module Malwack-main.zip 
Error : Copying zip to temp directory.  Unzip error .
Module downloaded from that site GitHub .

Magisk b38ab2a7 (27004)
Zygisk yes
Ramdisk yes
Application  b38ab2a7 (27004)
Paket com.topjohnwu.magisk 

Seal ROM V7.0.1 SM-N975F Android 14 ONEUI 6.0 

![SmartSelect_20240717_151811](https://github.com/user-attachments/assets/e2113abe-50f3-4561-9404-963466ffc4e1)

**Comment by daedaevibin** [comment]
> Cannot install module Malwack-main.zip 
> Error : Copying zip to temp directory.  Unzip error .
> Module downloaded from that site GitHub .
> 
> Magisk b38ab2a7 (27004)
> Zygisk yes
> Ramdisk yes
> Application  b38ab2a7 (27004)
> Paket com.topjohnwu.magisk 
> 
> Seal ROM V7.0.1 SM-N975F Android 14 ONEUI 6.0 
> 
> ![SmartSelect_20240717_151811](https://github.com/user-attachments/assets/e2113abe-50f3-4561-9404-963466ffc4e1)
> 

That Magisk version is Canary/beta (aka Developer/early release) and is not going to work in a lot of places for obvious reasons. Please use Stable before using as a daily system for rooting.

Aside from that, the fact you're using ONEUI 6.0, which is known to have compatibility issues.

**Comment by Person0z** [comment]
Please use the latest release of Magisk. Also, the module has been updated.
