### ISSUE TITLE
Tests fails

### ISSUE THREAD

**Issue by daedaevibin** [Magisk-Modules-Alt-Repo/Malwack#15]
This ad-blocker fails the Advanced Test from the canyoublockit website

https://canyoublockit.com/

I would like it to be updated to pass that as well if possible please. Thanks!!

From the advanced test on the website it fails:

Native Banners

pop-under ads

content blocker

Passes basic adblock detection, fails more advanced systems

Alternate Content Ads

**Comment by Person0z** [comment]
The module has not been updated since last year; I don't do rooting anymore; hence, I have not been able to update and have the correct format for the module.

**Comment by Person0z** [comment]
Updated

**Comment by daedaevibin** [comment]
> Updated

Ah, I see. In any case, thanks for your hard work :)

I would also like to know how I could download your hosts file or add it to Pihole as it says it's usable on windows as well (Either I missed a step there, or it doesn't work.) but still good work :)

**Comment by Person0z** [comment]
Go in system/etc/hosts and download the file and you should be able to upload it to pihole, as for windows, I'm not sure how to do that but I can help with Linux if you'd like

**Comment by daedaevibin** [comment]
> Go in system/etc/hosts and download the file and you should be able to upload it to pihole, as for windows, I'm not sure how to do that but I can help with Linux if you'd like

Ah, I'd like the instructions for doing so with PiHole please.

I don't have my device rooted anymore due to various, and widespread, complications (ALL ROMs have a single issue they share, making things not work properly)

And would enjoy if there was a way to download from here on GitHub, and add it that way?

**Comment by Person0z** [comment]
I don't know how to do it with PiHole. You can upload a host file, and PiHole can use that to block all things within that. There should be something on PiHole docs or a YouTube video that explains how to do this better than I can. 

You can download the hosts file to use in PiHole by going here and downloading it: https://raw.githubusercontent.com/Magisk-Modules-Alt-Repo/Malwack/main/system/etc/hosts
