### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by damondiamond** [Magisk-Modules-Alt-Repo/Malwack#17]
![Screenshot_20241023-013231](https://github.com/user-attachments/assets/e9239125-30bd-490b-a372-880e1cc19c98)

Magisk 28, I can't add to the white list, it works on version 27, I don't know if it depends on this or not

**Comment by daedaevibin** [comment]
Malwack --restore-default                              <
chmod: chmod '/etc/hosts' to 0644: Read-only file system
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -  0 37.3M    0  339k    0     0   428k      0  0:01:29 -  7 37.3M    7 3021k    0     0  1682k      0  0:00:22   18 37.3M   18 7248k    0     0  2595k      0  0:00:14   30 37.3M   30 11.2M    0     0  3045k      0  0:00:12   40 37.3M   40 15.2M    0     0  3257k      0  0:00:11   47 37.3M   47 17.8M    0     0  3162k      0  0:00:12   57 37.3M   57 21.5M    0     0  3247k      0  0:00:11   66 37.3M   66 24.7M    0     0  3248k      0  0:00:11   75 37.3M   75 28.2M    0     0  3285k      0  0:00:11   85 37.3M   85 31.9M    0     0  3344k      0  0:00:11   93 37.3M   93 34.9M    0     0  3315k      0  0:00:11  100 37.3M  100 37.3M    0     0  3298k      0  0:00:11  0:00:11 --:--:-- 3370k
rm: /etc/hosts: Read-only file system
Removed /etc/hosts
touch: '/etc/hosts': Read-only file system
Created /etc/hosts
chmod: chmod '/etc/hosts' to 0644: Read-only file system
Restored permissions for /etc/hosts
/system/bin/malwack[135]: can't create /etc/hosts: Read-only file system
Added entries from hosts.txt to /etc/hosts
Removed hosts.txt
Entry for https://raw.githubusercontent.com/Magisk-Modules-Alt-Repo/Malwack/main/system/etc/hosts added to /etc/hosts
alwack --whitelist s.youtube.com                      <
mv: /etc/hosts: Read-only file system
Error: Failed to replace /etc/hosts with the modified content.
Done

Same issues

**Comment by Person0z** [comment]
fixed
