### ISSUE TITLE
New update crashed Facebook and messenger 

### ISSUE THREAD

**Issue by cr4sh-me** [Magisk-Modules-Alt-Repo/Malwack#2]
New update broke Facebook and messenger app, there's message "something went wrong" after opening app, I tried clearing cache etc - nothing worked. After disabling module in magisk these apps are working back normally

**Comment by Person0z** [comment]
If you can wait until my school finishes. I'll check it out and see what happened.

**Comment by Person0z** [comment]
Hey, sorry about not being able to do this last week. Got caught up in school and a family emergency happened. Ill get it updated today. Again, sorry about that.

**Comment by Person0z** [comment]
Should be fixed, let me know if it works now!

**Comment by cr4sh-me** [comment]
> Should be fixed, let me know if it works now!

Yes, it's working now. Closing the issue
