### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by daniiii5** [Magisk-Modules-Alt-Repo/Malwack#4]
When I execute malwack --restore-default

![Screenshot_20230921-080155](https://github.com/Magisk-Modules-Alt-Repo/Malwack/assets/58140209/1ab3b178-67fd-4466-9f6f-4aac58826845)

**Comment by Person0z** [comment]
This is an issue with your Termux, you don't have ``curl`` installed. To install it: ``pkg install curl``. Then try the command again.

**Comment by BoyWithDanii** [comment]
> This is an issue with your Termux, you don't have `curl` installed. To install it: `pkg install curl`. Then try the command again.

![Screenshot_20230921-075354](https://github.com/Magisk-Modules-Alt-Repo/Malwack/assets/58140209/26be0538-0c87-46df-b1a3-85352f9620bd)

**Comment by daniiii5** [comment]
![Screenshot_20230921-080155](https://github.com/Magisk-Modules-Alt-Repo/Malwack/assets/58140209/62b413f7-df6d-433f-b378-156fe327788c)


> This is an issue with your Termux, you don't have `curl` installed. To install it: `pkg install curl`. Then try the command again.

**Comment by Person0z** [comment]
Reinstall the module to restore it then, as this is an error with Temux. It's out of my control. Also, did you install Temux with playstore or fdriod?

**Comment by daniiii5** [comment]
I installed it with play store

**Comment by Person0z** [comment]
> I installed it with play store

Install with F driod and that should fix your issue. Issue closed.

**Comment by BoyWithDanii** [comment]
Installed through fdroid, now curl doesn't even work even when reinstalling it.

![Uploading Screenshot_20230923-105036.png…]()

**Comment by daniiii5** [comment]
Installed through fdroid, now curl doesn't even work even when reinstalling it.

![Screenshot_20230923-105036](https://github.com/Magisk-Modules-Alt-Repo/Malwack/assets/58140209/00fec33e-c92a-462f-998f-614600e9753e)

**Comment by Person0z** [comment]
Sorry for the delayed response, this is an issue with Termux itself and I have no control over it, sadly. Please reinstall the module to revert it to normal.

**Comment by now0clock** [comment]
The OP is at the root# command prompt. They can have curl in Termux, but it will not be in their $PATH after typing su. The curl binary would have to be in system path.

You can check what your path is at any command prompt by doing:

echo $PATH

![Screenshot_20231026-170917](https://github.com/Magisk-Modules-Alt-Repo/Malwack/assets/59995403/778fa3ee-27b8-461f-a261-b72e082b2269)
