### ISSUE TITLE
org.codeaurora.ims.ImsApp crash 

### ISSUE THREAD

**Issue by HsiehYifang** [Magisk-Modules-Alt-Repo/Malwack#5]
After installing this module, org.codeaurora.ims.ImsApp keeps crashing after rebooting. It's normal after uninstall it.
oneplus 10 pro
oos13
kernelsu

**Comment by Person0z** [comment]
Im not sure, is there any error in logs in magisk?

**Comment by HsiehYifang** [comment]
I installed it with kernelsu, there is no problem with the installation, it should be a problem with the hostfile.

**Comment by Person0z** [comment]
I will update the module soon, along with the host file. Hopefully, that should fix your issue. Ill be updating soon either today or tomorrow.

**Comment by Person0z** [comment]
Done
