### ISSUE TITLE
YouTube does not retain history

### ISSUE THREAD

**Issue by BLADR-ONE** [Magisk-Modules-Alt-Repo/Malwack#6]
After installing this module, the history does not work anymore in the YouTube app.
Had the same problem with other host file based adblokers like AdAway.
The solution would be to whitelist m.youtube.com, and s.youtube.com, but malwack does not provide such a feature.

Android 13, October 21 security patch, lineage OS 20, lineage kernel 4.4+

**Comment by Person0z** [comment]
Hello, i will add a command via Termux which will allow users to whitelist domains. Ill try to get it done within the next update!

**Comment by BLADR-ONE** [comment]
Thanks , I'm waiting to hear from you when you solve it. Until then, take care ☺️

**Comment by Person0z** [comment]
Thank you! You have a great day and stay safe!

**Comment by Person0z** [comment]
Hey, just letting you know I have not forgotten about this. I'm on the verge of testing and bug fixing for next release!

**Comment by Person0z** [comment]
Done, use malwack --whitelist <domain>. Thanks!

**Comment by BLADR-ONE** [comment]
> Hey, just letting you know I have not forgotten about this. I'm on the verge of testing and bug fixing for next release!

Thank you so much for your time (and the bugfix). I appreciate you've written that you didn't forget about it, but it's not like i was demanding a fix :),so it was well welcomed even if it was to be after 10 months. Anyways was wondering if you had any intention in developing a companion app for this module. Maybe I could help with that. Take care!

**Comment by BLADR-ONE** [comment]
Also you might wanna add in the next version the --whitelist command in the help prompt ☺️.

**Comment by Person0z** [comment]
> > Hey, just letting you know I have not forgotten about this. I'm on the verge of testing and bug fixing for next release!
> 
> Thank you so much for your time (and the bugfix). I appreciate you've written that you didn't forget about it, but it's not like i was demanding a fix :),so it was well welcomed even if it was to be after 10 months. Anyways was wondering if you had any intention in developing a companion app for this module. Maybe I could help with that. Take care!

No problem, I'm trying to be a good developer and helping the community :)

So about the app, I have no idea how to code or make an app for android. If you want to help me out with this, let me know and we can chat further!

**Comment by Person0z** [comment]
> Also you might wanna add in the next version the --whitelist command in the help prompt ☺️.

~~Will do!~~

Done

**Comment by BLADR-ONE** [comment]
> > > Hey, just letting you know I have not forgotten about this. I'm on the verge of testing and bug fixing for next release!
> > 
> > Thank you so much for your time (and the bugfix). I appreciate you've written that you didn't forget about it, but it's not like i was demanding a fix :),so it was well welcomed even if it was to be after 10 months. Anyways was wondering if you had any intention in developing a companion app for this module. Maybe I could help with that. Take care!
> 
> No problem, I'm trying to be a good developer and helping the community :)
> 
> So about the app, I have no idea how to code or make an app for android. If you want to help me out with this, let me know and we can chat further!

I totally forgot that i have written this. Now i'm during my final school year and i need to lear this period till july to take the big test that will let me graduate high scool. Untill then i cannot really develop, but i'll message you when i'm done with all the exams so we can talk more. 

I have some experience with building apps in react native, wich runs the apps in a js vm wich makes it compatible on almost all platforms. Anyhow don't know how an application wich requires root and system modifications would function in react, or even if it would function at all, but I'm open to learn developing native apps too.
