### ISSUE TITLE
Anti-adblock

### ISSUE THREAD

**Issue by Vantesh** [Magisk-Modules-Alt-Repo/Malwack#8]
Is there any support for disabling the anti AdBlock feature on some website which force us to disable adblocker?

**Comment by DistroAgnostic** [comment]
> Is there any support for disabling the anti AdBlock feature on some website which force us to disable adblocker?

````
"Use: malwack --whitelist <domain>

"--whitelist <domain>: Remove the specified domain from the hosts file."

````

**Comment by Ccrlll** [comment]
> > Is there any support for disabling the anti AdBlock feature on some website which force us to disable adblocker?
> 
> ```
> "Use: malwack --whitelist <domain>
> 
> "--whitelist <domain>: Remove the specified domain from the hosts file."
> ```

Not working Permission denied
/system/bin/malwack[135]: sed: can't execute: Permission denied
Error: Failed to remove domain.name from /etc/hosts.

**Comment by Sheepmister** [comment]
i whitelist host the website and reboot my phone but still ad block detected im using chrome

**Comment by Person0z** [comment]
Whitelist removes websites that are being blocked, for example, if google.com is blocked from the file then you whitelist it itll allow google.com to show. It does not whitelist it to stop blocking the site. If you want to stop and turn on blocking you can enable the seamless module (i think that's what its called) and then run the command to stop blocking.
